=begin
#Practice -> Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: Bifrost@HenryScheinOne.com
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SlipstreamClient::LinksApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LinksApi' do
  before do
    # run before each test
    @api_instance = SlipstreamClient::LinksApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LinksApi' do
    it 'should create an instance of LinksApi' do
      expect(@api_instance).to be_instance_of(SlipstreamClient::LinksApi)
    end
  end

  # unit tests for create_short_links
  # Create short links
  # Creates shortened versions of one or more URLs
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param shorten_link_request The long links to shorten
  # @param [Hash] opts the optional parameters
  # @return [ShortLinksCreatedResponse]
  describe 'create_short_links test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_short_link
  # Delete Shortened Link
  # Deletes a shortened link by ID
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param link_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a shortened link
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_short_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_short_link
  # Get Shortened Link
  # Gets the details of a shortened link by ID
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param link_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a shortened link
  # @param [Hash] opts the optional parameters
  # @return [ShortenedLink]
  describe 'get_short_link test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_short_links
  # List Shortened Links
  # Lists active short links for the site
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size The page number to retrieve
  # @option opts [String] :next_page_token A token retrieved from a previous request, used to retrieve the next page of results
  # @option opts [Boolean] :is_visited If specified, filters the list to only links that are visited or unvisited. Omit to include all links
  # @option opts [Boolean] :has_click_tracking If specified, filters the list to only links that count clicks or don&#39;t count clicks. Omit to include all links
  # @return [ShortenedLinksListResponse]
  describe 'list_short_links test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
