=begin
#Practice -> Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: Bifrost@HenryScheinOne.com
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SlipstreamClient::LookupApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'LookupApi' do
  before do
    # run before each test
    @api_instance = SlipstreamClient::LookupApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of LookupApi' do
    it 'should create an instance of LookupApi' do
      expect(@api_instance).to be_instance_of(SlipstreamClient::LookupApi)
    end
  end

  # unit tests for lookup_slug
  # Lookup Slug
  # Fetches the pms specific id of a given organisation or practice in slipstream
  # @param slug The slug of a practice site or organisation
  # @param [Hash] opts the optional parameters
  # @return [PracticeEntity]
  describe 'lookup_slug test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
