=begin
#Practice -> Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: Bifrost@HenryScheinOne.com
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'spec_helper'
require 'json'

# Unit tests for SlipstreamClient::SiteDetailsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SiteDetailsApi' do
  before do
    # run before each test
    @api_instance = SlipstreamClient::SiteDetailsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SiteDetailsApi' do
    it 'should create an instance of SiteDetailsApi' do
      expect(@api_instance).to be_instance_of(SlipstreamClient::SiteDetailsApi)
    end
  end

  # unit tests for add_practice_site_capability
  # Add capability
  # Adds a single capability to the list of functionality that the practice site supports. See [Capabilities](#section/Getting-started/Capabilities) for more details.
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param capability The capability to add to the practice, see [Capabilities](#section/Getting-started/Capabilities) for more details.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'add_practice_site_capability test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_practice_site_logo
  # Delete practice site logo file
  # Deletes the logo file of a practice site in the Slipstream practice registry
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_practice_site_logo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_practice_site_privacy_policy
  # Delete practice site privacy policy document
  # Deletes the privacy policy document of a practice site in the Slipstream practice registry
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_practice_site_privacy_policy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_practice_site_details
  # Get practice site details
  # Fetches the full details of a practice site in the slipstream practice registry
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param [Hash] opts the optional parameters
  # @return [PracticeSiteDetails]
  describe 'get_practice_site_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_practice_site_capabilities
  # List capabilities
  # Fetches the list of functionality that a practice site (and the software it is using) supports. See [Capabilities](#section/Getting-started/Capabilities) for more details.
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param [Hash] opts the optional parameters
  # @return [CapabilitiesListResponse]
  describe 'list_practice_site_capabilities test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for practice_site_has_capability
  # Check capability
  # Checks if the practice supports a capability. See [Capabilities](#section/Getting-started/Capabilities) for more details.
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param capability The capability to add to the practice, see [Capabilities](#section/Getting-started/Capabilities) for more details.
  # @param [Hash] opts the optional parameters
  # @return [Boolean]
  describe 'practice_site_has_capability test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_practice_site_capability
  # Remove capability
  # Removes a capability from a practice. See [Capabilities](#section/Getting-started/Capabilities) for more details.
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param capability The capability to add to the practice, see [Capabilities](#section/Getting-started/Capabilities) for more details.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'remove_practice_site_capability test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_practice_site
  # Update practice site details
  # Updates the details of a practice site in the Slipstream practice registry
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param update_practice_site_details_request The details of the practice site to onboard
  # @param [Hash] opts the optional parameters
  # @return [PracticeSiteIdentity]
  describe 'update_practice_site test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_practice_site_logo
  # Update practice site logo
  # Updates the logo of a practice site in the Slipstream practice registry
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param [Hash] opts the optional parameters
  # @option opts [File] :file Logo file for the practice
  # @return [PracticeFileUploaded]
  describe 'update_practice_site_logo test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_practice_site_privacy_policy
  # Update practice site privacy policy
  # Updates the privacy policy of a practice site in the Slipstream practice registry
  # @param site_slug The Slipstream [slug](https://sqids.org/) that uniquely identifies a physical practice
  # @param [Hash] opts the optional parameters
  # @option opts [File] :file Privacy policy document for the practice
  # @return [PracticeFileUploaded]
  describe 'update_practice_site_privacy_policy test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
