=begin
#Slipstream Filtered API (Physical Post, SMS, Billing)

#Filtered Slipstream API containing only Physical Post, SMS, Billing, and webhook endpoints

The version of the OpenAPI document: 1.0.0-filtered
Contact: Bifrost@HenryScheinOne.com
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

module SlipstreamClient
  VERSION = '1.0.0'
end
