=begin
#Practice -> Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: Bifrost@HenryScheinOne.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'date'
require 'time'

module SlipstreamClient
  class EmailStatus
    UNKNOWN = "Unknown".freeze
    PENDING = "Pending".freeze
    SUCCESS = "Success".freeze
    FAILED = "Failed".freeze
    CANCELLED = "Cancelled".freeze

    def self.all_vars
      @all_vars ||= [UNKNOWN, PENDING, SUCCESS, FAILED, CANCELLED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if EmailStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #EmailStatus"
    end
  end
end
