=begin
#Slipstream Filtered API (Physical Post, SMS, Billing)

#Filtered Slipstream API containing only Physical Post, SMS, Billing, and webhook endpoints

The version of the OpenAPI document: 1.0.0-filtered
Contact: Bifrost@HenryScheinOne.com
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SlipstreamClient::Addressee
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SlipstreamClient::Addressee do
  let(:instance) { SlipstreamClient::Addressee.new }

  describe 'test an instance of Addressee' do
    it 'should create an instance of Addressee' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(SlipstreamClient::Addressee)
    end
  end

  describe 'test attribute "pms_specific_id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "given_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "middle_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "family_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "full_name"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
