=begin
#Practice -> Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: Bifrost@HenryScheinOne.com
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SlipstreamClient::EmailStatus
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SlipstreamClient::EmailStatus do
  let(:instance) { SlipstreamClient::EmailStatus.new }

  describe 'test an instance of EmailStatus' do
    it 'should create an instance of EmailStatus' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(SlipstreamClient::EmailStatus)
    end
  end

end
