=begin
#Slipstream Filtered API (Physical Post, SMS, Billing)

#Filtered Slipstream API containing only Physical Post, SMS, Billing, and webhook endpoints

The version of the OpenAPI document: 1.0.0-filtered
Contact: Bifrost@HenryScheinOne.com
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SlipstreamClient::PhysicalPostSent
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SlipstreamClient::PhysicalPostSent do
  let(:instance) { SlipstreamClient::PhysicalPostSent.new }

  describe 'test an instance of PhysicalPostSent' do
    it 'should create an instance of PhysicalPostSent' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(SlipstreamClient::PhysicalPostSent)
    end
  end

  describe 'test attribute "succeeded"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "failed"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
