=begin
#Practice -> Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: Bifrost@HenryScheinOne.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SlipstreamClient::PractitionersUploadResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SlipstreamClient::PractitionersUploadResponse do
  let(:instance) { SlipstreamClient::PractitionersUploadResponse.new }

  describe 'test an instance of PractitionersUploadResponse' do
    it 'should create an instance of PractitionersUploadResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(SlipstreamClient::PractitionersUploadResponse)
    end
  end

  describe 'test attribute "warnings"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "results"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
