=begin
#Practice -> Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: Nexus@HenryScheinOne.co.nz
Generated by: https://openapi-generator.tech
Generator version: 7.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::PracticeManagementSoftware
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::PracticeManagementSoftware do
  let(:instance) { OpenapiClient::PracticeManagementSoftware.new }

  describe 'test an instance of PracticeManagementSoftware' do
    it 'should create an instance of PracticeManagementSoftware' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::PracticeManagementSoftware)
    end
  end

end
