=begin
#Practice -> Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: Bifrost@HenryScheinOne.com
Generated by: https://openapi-generator.tech
Generator version: 7.8.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SlipstreamClient::ProviderType
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SlipstreamClient::ProviderType do
  let(:instance) { SlipstreamClient::ProviderType.new }

  describe 'test an instance of ProviderType' do
    it 'should create an instance of ProviderType' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(SlipstreamClient::ProviderType)
    end
  end

end
