=begin
#Practice -> Cloud API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Contact: Bifrost@HenryScheinOne.com
Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SlipstreamClient::UploadAvailabilityRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe SlipstreamClient::UploadAvailabilityRequest do
  let(:instance) { SlipstreamClient::UploadAvailabilityRequest.new }

  describe 'test an instance of UploadAvailabilityRequest' do
    it 'should create an instance of UploadAvailabilityRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(SlipstreamClient::UploadAvailabilityRequest)
    end
  end

  describe 'test attribute "availability"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "is_full_upload"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
